source "http://rubygems.org"

#gem 'jekyll', :git => 'https://github.com/mojombo/jekyll.git'
gem 'jekyll'
gem 'mustache'
gem 'jekyll-less'
gem 'therubyracer'
gem 'rdiscount'
# gem 'redcarpet', '~> 2.3'
# gem 'albino', '~> 1.3'
gem 'RedCloth'
gem 'pygments.rb'
gem 'thin'
gem 'liquid'
gem 'ruby-aaws'
gem 'nokogiri'
gem 'iconv'
